# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.FileField(upload_to='materials')),
            ],
            options={
                'ordering': ('date', 'title'),
            },
        ),
    ]
