# Generated by Django 4.2.1 on 2023-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
