# Generated by Django 4.2.1 on 2023-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='custom_module_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='custom_module_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
