# Generated by Django 4.2.1 on 2024-11-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_custom_module_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challengecomment'),
        ),
    ]
