#!/bin/bash

# Prepare Django by migrating and collecting static files
python3 /var/shrubbery/manage.py migrate --no-input
python3 /var/shrubbery/manage.py collectstatic --noinput --clear

# Run Redis and Celery
redis-server --daemonize yes
celery -A shrubbery worker -l DEBUG --logfile=celery_worker.log --detach
celery -A shrubbery beat -l DEBUG --logfile=celery_beat.log --detach

# Start Gunicorn + Nginx
gunicorn -c gunicorn_conf.py
nginx -g 'daemon off;'
