# Generated by Django 4.2.1 on 2023-05-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0001_initial'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpoints',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher'),
        ),
    ]
