# Generated by Django 4.2.1 on 2023-05-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherpoints',
            name='points_ptr',
        ),
        migrations.RemoveField(
            model_name='voucherpoints',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='VoucherPoints',
        ),
    ]
