# Generated by Django 4.2.1 on 2023-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilepicturepoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicturepoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
