# Generated by Django 4.2.1 on 2023-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('LGH', 'Light'), ('DRK', 'Dark')], default='LGH', max_length=3),
        ),
    ]
