# Generated by Django 4.2.1 on 2023-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profilepicturepoints_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification_challenge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification_forum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification_homework',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification_news',
            field=models.BooleanField(default=True),
        ),
    ]
