# Generated by Django 4.2.1 on 2023-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_norification_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification_solution_comments',
            field=models.BooleanField(default=True),
        ),
    ]
