# Generated by Django 4.2.1 on 2023-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-date',)},
        ),
    ]
