# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('points', models.IntegerField(default=10)),
                ('sanity_test', models.TextField()),
                ('full_test', models.TextField(blank=True, default='', null=True)),
                ('custom_module_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('custom_module_content', models.TextField(blank=True, default='', null=True)),
                ('hidden', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('executing_tests', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='HomeworkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('starred', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
