# Generated by Django 4.2.1 on 2023-05-19 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('sanity_test', models.TextField()),
                ('full_test', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
    ]
