# Generated by Django 4.2.1 on 2023-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_alter_homework_sanity_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
