# Generated by Django 4.2.1 on 2023-11-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0008_homework_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='custom_module_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='custom_module_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
