# Generated by Django 4.2.1 on 2024-11-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_homework_custom_module_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeworks.homeworkcomment'),
        ),
    ]
