# Generated by Django 4.2.1 on 2024-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_homework_custom_module_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='first_reveal',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
