# Generated by Django 4.2.1 on 2024-09-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_email_notification_solution_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='KingArthur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('achieved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
