# Generated by Django 4.2.1 on 2023-05-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ('-date',)},
        ),
    ]
