# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('NA', 'News Article'), ('F', 'Forum'), ('FC', 'Forum Comment'), ('HW', 'Homework'), ('HWC', 'Homework Comment'), ('HWS', 'Homework Solution'), ('HWSU', 'Homework Solution Update'), ('HWSC', 'Homework Solution Comment'), ('HWSIC', 'Homework Solution Inline Comment'), ('C', 'Challenge'), ('CC', 'Challenge Comment'), ('CS', 'Challenge Solution'), ('CSU', 'Challenge Solution Update'), ('CSC', 'Challenge Solution Comment'), ('FSC', 'Final Schedule flip')], default=None, max_length=5, null=True)),
                ('forced_seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
