# Generated by Django 4.2.1 on 2023-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('NA', 'New Article'), ('HW', 'Homework'), ('HWC', 'Homework Comment'), ('HWS', 'Homework Solution'), ('HWSC', 'Homework Solution Comment'), ('C', 'Challenge'), ('CC', 'Challenge Comment'), ('CS', 'Challenge Solution'), ('CSC', 'Challenge Solution Comment'), ('F', 'Forum'), ('FC', 'Forum Comment')], default=None, max_length=5, null=True),
        ),
    ]
