# Generated by Django 4.2.1 on 2023-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('NA', 'News Article'), ('F', 'Forum'), ('FC', 'Forum Comment'), ('HW', 'Homework'), ('HWC', 'Homework Comment'), ('HWS', 'Homework Solution'), ('HWSC', 'Homework Solution Comment'), ('C', 'Challenge'), ('CC', 'Challenge Comment'), ('CS', 'Challenge Solution'), ('CSC', 'Challenge Solution Comment')], default=None, max_length=5, null=True),
        ),
    ]
