# Generated by Django 4.2.1 on 2023-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='forced_seen',
            field=models.BooleanField(default=False),
        ),
    ]
