# Generated by Django 4.2.1 on 2023-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumcomment_points_forumcomment_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
