# Generated by Django 4.2.1 on 2023-10-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumcomment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomment'),
        ),
    ]
