# Generated by Django 4.2.1 on 2023-10-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomment'),
        ),
    ]
