# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('homeworks', '0002_initial'),
        ('homeworksolutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolutioninlinecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksolutioninlinecomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution'),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistoryinlinecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistoryinlinecomment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolutionhistory'),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistoryinlinecomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution'),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution'),
        ),
        migrations.AddField(
            model_name='homeworksolutioncomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksolutioncomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution'),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework'),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_homeworks', to='users.teacher'),
        ),
    ]
