# Generated by Django 4.2.1 on 2023-05-19 11:14

from django.db import migrations, models
import homeworksolutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksolution',
            name='content',
            field=models.FileField(upload_to=homeworksolutions.models.get_upload_path),
        ),
    ]
