# Generated by Django 4.2.1 on 2023-05-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0003_alter_homeworksolution_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksolution',
            name='history',
        ),
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution'),
        ),
    ]
