# Generated by Django 4.2.1 on 2023-05-22 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworksolutions', '0005_alter_homeworksolutionhistory_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSolutionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('starred', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('homework_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworksolutions.homeworksolution')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
