# Generated by Django 4.2.1 on 2023-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0009_rename_results_homeworksolution_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='failed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='passed_tests',
            field=models.IntegerField(default=0),
        ),
    ]
