# Generated by Django 4.2.1 on 2023-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0011_homeworksolution_line_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='diff',
            field=models.TextField(default=''),
        ),
    ]
