# Generated by Django 4.2.1 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_notification_solution_comments'),
        ('homeworksolutions', '0017_remove_homeworksolutionteacherpoints_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_homeworks', to='users.teacher'),
        ),
    ]
