# Generated by Django 4.2.1 on 2023-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0020_alter_homeworksolution_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='commit_message',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homeworksolutionhistory',
            name='commit_message',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
