# Generated by Django 4.2.1 on 2024-01-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworksolutions', '0021_homeworksolution_commit_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='internal_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
