# Generated by Django 4.2.1 on 2023-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
