# Generated by Django 4.2.1 on 2023-05-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_points_alter_voucher_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='points',
        ),
    ]
