# Generated by Django 4.2.1 on 2023-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_remove_voucher_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
