# Generated by Django 4.2.1 on 2023-05-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vouchers', '0004_voucher_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='amount',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
    ]
