# Generated by Django 4.2.1 on 2023-05-17 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_rename_amount_voucher_points_alter_voucher_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='taken_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
