# Generated by Django 4.2.1 on 2023-05-17 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_rename_taken_date_voucher_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
