# Generated by Django 4.2.1 on 2023-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_alter_voucher_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ('owner', 'date')},
        ),
    ]
