# Generated by Django 4.2.1 on 2024-01-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_notification_solution_comments'),
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalexchange',
            name='confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_confirmations', to='users.student'),
        ),
        migrations.AlterField(
            model_name='finalexchange',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='users.student'),
        ),
    ]
