# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscheduleslot',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.student'),
        ),
        migrations.AddField(
            model_name='finalexchange',
            name='confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_confirmations', to='users.student'),
        ),
        migrations.AddField(
            model_name='finalexchange',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='users.student'),
        ),
    ]
