# Generated by Django 4.2.1 on 2025-01-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('challengesolutions', '0001_initial'),
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesolutioninlinecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesolutioninlinecomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengesolutions.challengesolution'),
        ),
        migrations.AddField(
            model_name='challengesolutionhistoryinlinecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesolutionhistoryinlinecomment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengesolutions.challengesolutionhistory'),
        ),
        migrations.AddField(
            model_name='challengesolutionhistoryinlinecomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengesolutions.challengesolution'),
        ),
        migrations.AddField(
            model_name='challengesolutionhistory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesolutionhistory',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challengesolutionhistory',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengesolutions.challengesolution'),
        ),
        migrations.AddField(
            model_name='challengesolutioncomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesolutioncomment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengesolutions.challengesolution'),
        ),
        migrations.AddField(
            model_name='challengesolution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesolution',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challengesolution',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_challenges', to='users.teacher'),
        ),
    ]
