# Generated by Django 4.2.1 on 2023-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengesolutions', '0003_alter_challengesolution_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesolution',
            name='commit_message',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='challengesolutionhistory',
            name='commit_message',
            field=models.TextField(default='', max_length=50),
        ),
    ]
