# Generated by Django 4.2.1 on 2023-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengesolutions', '0004_challengesolution_commit_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesolution',
            name='commit_message',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challengesolutionhistory',
            name='commit_message',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
