# Generated by Django 4.2.1 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengesolutions', '0005_alter_challengesolution_commit_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesolution',
            name='internal_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
